### ISSUE TITLE
phpunit.de server 403 to GitHub runners

### ISSUE THREAD

**Issue by shyim** [sebastianbergmann/phpunit-website#71] opened 2024-12-03 08:55 UTC
Hey,

I have a few pipelines failing due to:

```

PHP Warning:  DOMDocument::schemaValidate(https://schema.phpunit.de/10.1/phpunit.xsd): Failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
 in /home/runner/work/app-bundle-symfony/app-bundle-symfony/vendor/infection/infection/src/TestFramework/PhpUnit/Config/XmlConfigurationManipulator.php on line 187
PHP Warning:  DOMDocument::schemaValidate(): Invalid Schema in /home/runner/work/app-bundle-symfony/app-bundle-symfony/vendor/infection/infection/src/TestFramework/PhpUnit/Config/XmlConfigurationManipulator.php on line 187
```

locally I can download that file, but my GitHub actions seem not able to download it. Did some firewall rules changed on phpunit.de ?

**Comment by sebastianbergmann** [comment] 2024-12-03 10:10
AFAIK, nothing has changed with regards to firewall rules on phpunit.de (which are managed by/through Cloudflare).

My recommendation would be to not download the schema every single time you run your tests. For example, when you install PHPUnit using Composer, simply use `vendor/phpunit/phpunit/phpunit.xsd` as the path to the schema file in your XML configuration file.

Duplicate of #70.

**Closed by sebastianbergmann** 2024-12-03 10:10 UTC

**Comment by sebastianbergmann** [comment] 2024-12-03 16:39
I have contacted Cloudflare and the issue might already be fixed. If it is not, it would help to see the HTTP headers, most importantly the `CF-RAY` header, that is sent by Cloudflare for the HTTP request from GitHub Actions to `https://schema.phpunit.de`.
